/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ARate: typeof import('@arco-design/web-vue')['Rate']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Counter: typeof import('./src/components/Counter.vue')['default']
  }
}
